build:
  stage: build
  script:
    - which java
    - java -version
    - export
    - ./gradlew -Dorg.gradle.daemon=false -Dfile.encoding=UTF-8 assemble
  artifacts:
    paths:
      - build/libs/*.war
    expire_in: 1 day
  only:
    - branches

部署测试环境:
  stage: deploy
  variables:
    WAR: backend-0.1.war
    SERVICE: zhusu-backend
    REMOTE_HOST: 47.110.130.153
    REMOTE_DIR: /usr/local/zhusu
    URL: 47.110.130.153
  script:
    - '[ ! -f "build/libs/${WAR}" ] && ./gradlew -Dorg.gradle.daemon=false -Dfile.encoding=UTF-8 assemble'
    - rsync -e "ssh -o StrictHostKeyChecking=no" "build/libs/${WAR}" root@${REMOTE_HOST}:"/tmp/${WAR}"
    - ssh -o StrictHostKeyChecking=no root@${REMOTE_HOST} "systemctl stop ${SERVICE} && mv '${REMOTE_DIR}/${WAR}' '${REMOTE_DIR}/${WAR}.bak'; mv '/tmp/${WAR}' '${REMOTE_DIR}/${WAR}' && systemctl start ${SERVICE}"
    - for i in $(seq 15); do curl -sfL --connect-timeout 30 "${URL}" && exit || sleep 5; done && exit 1
  environment:
    name: stage
    url: ${URL}
  dependencies:
    - build
  only:
    - branches@yizhilee/backend
