build:
  stage: build
  script:
    - which java
    - java -version
    - export
    - ./gradlew -Dorg.gradle.daemon=false -Dfile.encoding=UTF-8 assemble
  artifacts:
    paths:
      - build/libs/*.war
    expire_in: 1 day
  only:
    - branches

test:
  stage: test
  variables:
    PGHOST: 47.96.6.65
    PGDATABASE: zhusu_test
    PGUSER: zhusu_admin
    PGPASSWORD: admin
  script:
    - which java
    - java -version
    - export
    - psql -c '\q'
    - ./gradlew -Dorg.gradle.daemon=false -Dfile.encoding=UTF-8 check

部署测试环境:
  stage: deploy
  variables:
    WAR: backend-0.1.war
    SERVICE: jupiter-backend
    REMOTE_HOST: api.aqiuyi.com
    REMOTE_DIR: /usr/local/jupiter
    URL: https://jupiter-backend.shifudao.com/
  script:
    - '[ ! -f "build/libs/${WAR}" ] && ./gradlew -Dorg.gradle.daemon=false -Dfile.encoding=UTF-8 assemble'
    - rsync -e "ssh -o StrictHostKeyChecking=no" "build/libs/${WAR}" root@${REMOTE_HOST}:"/tmp/${WAR}"
    - ssh -o StrictHostKeyChecking=no root@${REMOTE_HOST} "systemctl stop ${SERVICE} && mv '${REMOTE_DIR}/${WAR}' '${REMOTE_DIR}/${WAR}.bak'; mv '/tmp/${WAR}' '${REMOTE_DIR}/${WAR}' && systemctl start ${SERVICE}"
    - for i in $(seq 15); do curl -sfL --connect-timeout 30 "${URL}" && exit || sleep 5; done && exit 1
  when: manual
  environment:
    name: stage
    url: ${URL}
  dependencies:
    - build
  only:
    - branches@jupiter/backend
